### PR TITLE
Vep 113.3 v1

### PR DESCRIPTION
**Pull request by malachig**
Update to v113 of the Ensembl VEP software.

### CODE REVIEW

**Review by tmooney — APPROVED** [review]
+1 looks okay to me!

**Review by chrisamiller — APPROVED** [review]
Assuming that it's been tested, +1

**Review by johnegarza — APPROVED** [review]
The new image and all downloaded plugin files exist, looks good to me

**Comment by malachig** [comment]
Testing was successful.

**Pull request merged**
